/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication9;

/**
 *
 * @author andyq
 */
public class calendario extends javax.swing.JFrame {

    enfermera1 enf = new enfermera1();

    /**
     * Creates new form calendario
     */
    public calendario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        juanButton = new javax.swing.JButton();
        luisButton = new javax.swing.JButton();
        eduardoButton = new javax.swing.JButton();
        guadalupeButton = new javax.swing.JButton();
        mariaButton = new javax.swing.JButton();
        marielaButton = new javax.swing.JButton();
        lornaButton = new javax.swing.JButton();
        miriamButton = new javax.swing.JButton();
        lidiaButton = new javax.swing.JButton();
        juanaButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtStaffChar = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        juanButton.setText("Juan Perez");
        juanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                juanButtonActionPerformed(evt);
            }
        });

        luisButton.setText("Luis Gutierrez");
        luisButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                luisButtonActionPerformed(evt);
            }
        });

        eduardoButton.setText("Eduardo Gonzales");
        eduardoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eduardoButtonActionPerformed(evt);
            }
        });

        guadalupeButton.setText("Guadalupe Torres");
        guadalupeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guadalupeButtonActionPerformed(evt);
            }
        });

        mariaButton.setText("Maria Castillo");
        mariaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mariaButtonActionPerformed(evt);
            }
        });

        marielaButton.setText("Mariela Rodriguez");
        marielaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                marielaButtonActionPerformed(evt);
            }
        });

        lornaButton.setText("Lorna Suarez");
        lornaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lornaButtonActionPerformed(evt);
            }
        });

        miriamButton.setText("Miriam Garcia");
        miriamButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miriamButtonActionPerformed(evt);
            }
        });

        lidiaButton.setText("Lidia Mendez");
        lidiaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lidiaButtonActionPerformed(evt);
            }
        });

        juanaButton.setText("Juana Lopez");
        juanaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                juanaButtonActionPerformed(evt);
            }
        });

        txtStaffChar.setColumns(20);
        txtStaffChar.setRows(5);
        jScrollPane1.setViewportView(txtStaffChar);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(juanaButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lidiaButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(luisButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(eduardoButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                        .addComponent(guadalupeButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(mariaButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(marielaButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(juanButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(lornaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(miriamButton, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(juanButton)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(luisButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                        .addComponent(eduardoButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(guadalupeButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(mariaButton)
                        .addGap(18, 18, 18)
                        .addComponent(juanaButton)
                        .addGap(18, 18, 18)
                        .addComponent(lidiaButton)
                        .addGap(18, 18, 18)
                        .addComponent(miriamButton)
                        .addGap(18, 18, 18)
                        .addComponent(lornaButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(marielaButton)
                        .addGap(5, 5, 5))
                    .addComponent(jScrollPane1))
                .addGap(71, 71, 71))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
doctors doc = new doctors();
    private void juanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_juanButtonActionPerformed
        int button = 1;
        doc.getChar(button);
        String name = doc.getName();
        String nit = doc.getNit();
        String dpi = doc.getDPI();
        String col = doc.getCOL();
        int sal = doc.getSAL();
        String esp = doc.getStatus();

        txtStaffChar.setText(" El/La Doctor(a) " + name + " tiene el nit " + nit + ".\n Su DPI es " + dpi + " y su colegiado es el numero " + col + ".\n Su salario actual es de " + sal + " y " + esp + " es especialista.");
    }//GEN-LAST:event_juanButtonActionPerformed

    private void eduardoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eduardoButtonActionPerformed
        int button = 3;
        doc.getChar(button);
        String name = doc.getName();
        String nit = doc.getNit();
        String dpi = doc.getDPI();
        String col = doc.getCOL();
        int sal = doc.getSAL();
        String esp = doc.getStatus();

        txtStaffChar.setText(" El/La Doctor(a) "
                + name + " tiene el nit " + nit + ".\n Su DPI es "
                + dpi + " y su colegiado es el numero " + col + ".\n Su salario actual es de "
                + sal + " y " + esp + " es especialista.");
    }//GEN-LAST:event_eduardoButtonActionPerformed

    private void luisButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_luisButtonActionPerformed
        int button = 2;
        doc.getChar(button);
        String name = doc.getName();
        String nit = doc.getNit();
        String dpi = doc.getDPI();
        String col = doc.getCOL();
        int sal = doc.getSAL();
        String esp = doc.getStatus();

        txtStaffChar.setText(" El/La Doctor(a) " + name + " tiene el nit " + nit + ".\n Su DPI es " + dpi + " y su colegiado es el numero " + col + ".\n Su salario actual es de " + sal + " y " + esp + " es especialista.");
    }//GEN-LAST:event_luisButtonActionPerformed

    private void guadalupeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guadalupeButtonActionPerformed
        int button = 4;
        doc.getChar(button);
        String name = doc.getName();
        String nit = doc.getNit();
        String dpi = doc.getDPI();
        String col = doc.getCOL();
        int sal = doc.getSAL();
        String esp = doc.getStatus();

        txtStaffChar.setText(" El/La Doctor(a) "
                + name + " tiene el nit " + nit + ".\n Su DPI es "
                + dpi + " y su colegiado es el numero " + col + ".\n Su salario actual es de "
                + sal + " y " + esp + " es especialista.");        // TODO add your handling code here:
    }//GEN-LAST:event_guadalupeButtonActionPerformed

    private void mariaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mariaButtonActionPerformed
        int button = 5;
        doc.getChar(button);
        String name = doc.getName();
        String nit = doc.getNit();
        String dpi = doc.getDPI();
        String col = doc.getCOL();
        int sal = doc.getSAL();
        String esp = doc.getStatus();

        txtStaffChar.setText(" El/La Doctor(a) "
                + name + " tiene el nit " + nit + ".\n Su DPI es "
                + dpi + " y su colegiado es el numero " + col + ".\n Su salario actual es de "
                + sal + " y " + esp + " es especialista.");        // TODO add your handling code here:
    }//GEN-LAST:event_mariaButtonActionPerformed

    private void juanaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_juanaButtonActionPerformed
        int button = 5;
        doc.getChar(button);
        String name = enf.getName();
        String nit = enf.getNit();
        String dpi = enf.getDPI();
        String inte = enf.getInt();
        String sal = enf.getSAL();
        String age = enf.getAge();

        txtStaffChar.setText("La enfermera "
                + name + " tiene el nit " + nit + ".\n Su DPI es "
                + dpi + " y " + inte + " es intensiva.\n Su salario actual es de "
                + sal + " y lleva trabajando durante " + age + " anios.");
    }//GEN-LAST:event_juanaButtonActionPerformed

    private void lidiaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lidiaButtonActionPerformed
        int button = 6;
        doc.getChar(button);
        String name = enf.getName();
        String nit = enf.getNit();
        String dpi = enf.getDPI();
        String inte = enf.getInt();
        String sal = enf.getSAL();
        String age = enf.getAge();

        txtStaffChar.setText("La enfermera "
                + name + " tiene el nit " + nit + ".\n Su DPI es "
                + dpi + " y " + inte + " es intensiva.\n Su salario actual es de "
                + sal + " y lleva trabajando durante " + age + " anios.");
    }//GEN-LAST:event_lidiaButtonActionPerformed

    private void miriamButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miriamButtonActionPerformed
        int button = 7;
        doc.getChar(button);
        String name = enf.getName();
        String nit = enf.getNit();
        String dpi = enf.getDPI();
        String inte = enf.getInt();
        String sal = enf.getSAL();
        String age = enf.getAge();

        txtStaffChar.setText("La enfermera "
                + name + " tiene el nit " + nit + ".\n Su DPI es "
                + dpi + " y " + inte + " es intensiva.\n Su salario actual es de "
                + sal + " y lleva trabajando durante " + age + " anios.");
    }//GEN-LAST:event_miriamButtonActionPerformed

    private void lornaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lornaButtonActionPerformed
        int button = 8;
        doc.getChar(button);
        String name = enf.getName();
        String nit = enf.getNit();
        String dpi = enf.getDPI();
        String inte = enf.getInt();
        String sal = enf.getSAL();
        String age = enf.getAge();

        txtStaffChar.setText("La enfermera "
                + name + " tiene el nit " + nit + ".\n Su DPI es "
                + dpi + " y " + inte + " es intensiva.\n Su salario actual es de "
                + sal + " y lleva trabajando durante " + age + " anios.");
    }//GEN-LAST:event_lornaButtonActionPerformed

    private void marielaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_marielaButtonActionPerformed
        int button = 9;
        doc.getChar(button);
        String name = enf.getName();
        String nit = enf.getNit();
        String dpi = enf.getDPI();
        String inte = enf.getInt();
        String sal = enf.getSAL();
        String age = enf.getAge();

        txtStaffChar.setText("La enfermera "
                + name + " tiene el nit " + nit + ".\n Su DPI es "
                + dpi + " y " + inte + " es intensiva.\n Su salario actual es de "
                + sal + " y lleva trabajando durante " + age + " anios.");
    }//GEN-LAST:event_marielaButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(calendario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(calendario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(calendario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(calendario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new calendario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton eduardoButton;
    private javax.swing.JButton guadalupeButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton juanButton;
    private javax.swing.JButton juanaButton;
    private javax.swing.JButton lidiaButton;
    private javax.swing.JButton lornaButton;
    private javax.swing.JButton luisButton;
    private javax.swing.JButton mariaButton;
    private javax.swing.JButton marielaButton;
    private javax.swing.JButton miriamButton;
    private javax.swing.JTextArea txtStaffChar;
    // End of variables declaration//GEN-END:variables
}
